/* Automatically generated by chibi-ffi; version: 0.3 */

#include <chibi/eval.h>
#include <stdio.h>
/*
types: ()
enums: ()
*/


void foo(int a) {
	printf("%d\n", a+1);
}

static sexp sexp_foo_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0) {
  sexp res;
  if (! sexp_exact_integerp(arg0))
    return sexp_type_exception(ctx, self, SEXP_FIXNUM, arg0);
  res = ((foo(sexp_sint_value(arg0))), SEXP_VOID);
  return res;
}

int main(int argc, char** argv) {

	sexp ctx;
	ctx = sexp_make_eval_context(NULL, NULL, NULL, 0, 0);
	sexp_load_standard_env(ctx, NULL, SEXP_SEVEN);
	sexp_load_standard_ports(ctx, NULL, stdin, stdout, stderr, 0);

	/*sexp_gc_var3(name, tmp, op);
	sexp_gc_preserve3(ctx, name, tmp, op);*/
	sexp env = sexp_context_env(ctx);
	sexp_define_foreign(ctx, env, "foo", 1, (sexp_proc1)sexp_foo_stub);
	//op = sexp_define_foreign(ctx, NULL, "foo", 1, (sexp_proc1)sexp_foo_stub);
	/*if (sexp_opcodep(op)) {
		sexp_opcode_return_type(op) = SEXP_VOID;
		sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
	}
	sexp_gc_release3(ctx);*/

	//declare and preserve local variables
	//sexp_gc_var2(obj1, obj2);
	//sexp_gc_preserve2(ctx, obj1, obj2);

	//eval a C string as Scheme code
	sexp_eval_string(ctx, "(foo 2)", -1, NULL);

	//construct a Scheme expression to eval
	//obj1 = sexp_intern(ctx, "my-procedure", -1);
	//obj2 = sexp_cons(ctx, obj1, SEXP_NULL);
	//sexp_eval(ctx, obj2, NULL);

	//release the local variables
	//sexp_gc_release2(ctx);

	sexp_destroy_context(ctx);
}
